[General-01]
network = VideoStreamingShowcase
scheduler-class = "inet::RealTimeScheduler"

**.crcMode = "computed"
**.fcsMode = "computed"

*.host1.eth[0].typename = "ExtUpperEthernetInterface"
*.host1.eth[0].device = "tapa"
*.host1.eth[0].copyConfiguration = "copyFromExt"

*.host2.eth[0].typename = "ExtUpperEthernetInterface"
*.host2.eth[0].device = "tapb"
*.host2.eth[0].copyConfiguration = "copyFromExt"

*.configurator.config = xml("<config> \
                                <interface hosts='router' names='eth0' address='192.168.2.99' netmask='255.255.255.0'/> \
                                <interface hosts='router' names='eth1' address='192.168.3.99' netmask='255.255.255.0'/> \
                             </config>")
*.router.ipv4.natTable.config = xml("<config> \
                                        <entry type='prerouting' \
                                        packetFilter='has(Ipv4Header) &amp;&amp; Ipv4Header.protocolId != 1 &amp;&amp; Ipv4Header.destAddress.str() == \"192.168.2.99\"' \
                                        srcAddress='192.168.3.99' destAddress='192.168.3.20'/> \
                                       <entry type='prerouting' \
                                        packetFilter='has(Ipv4Header) &amp;&amp; Ipv4Header.protocolId != 1 &amp;&amp; Ipv4Header.destAddress.str() == \"192.168.3.99\"' \
                                        srcAddress='192.168.2.99' destAddress='192.168.2.20'/> \
                                     </config>")

*.visualizer.*.interfaceTableVisualizer.displayInterfaceTables = true
*.visualizer.*.interfaceTableVisualizer.nodeFilter = "not name=~switch*"

**.duplexMode = true
**.eth*.bitrate = 100Mbps


#-----------------------------------------------------------------------------

[General-02]
description = "(PER = 0.01 e Delay=50ms)"
extends = General-01

**.switch2.ethg*[*].channel.per=0.01 
**.switch2.ethg*[*].channel.delay=50ms

[General-03]
description = "(PER = 0.5 e Delay=50ms)"
extends = General-01

**.switch2.ethg*[*].channel.per=0.5
**.switch2.ethg*[*].channel.delay=10ms

[General-04]
description = "(PER = 0.01 e delay=300ms)"
extends = General-01

**.switch2.ethg*[*].channel.per=0.01 
**.switch2.ethg*[*].channel.delay=300ms

[General-05]
description = "(PER = 0.5 e delay= 300ms)"
extends = General-01

**.switch2.ethg*[*].channel.per=0.5 
**.switch2.ethg*[*].channel.delay=300ms

[General]

scheduler-class = "inet::RealTimeScheduler"

**.debug = true
**.verbose = true
**.trace = true
**.recordEventlog = true

**.crcMode = "computed"
**.fcsMode = "computed"

*.tapa.useServiceDiscovery = true
*.tapb.useServiceDiscovery = true

*.host1.eth[0].typename = "ExtUpperEthernetInterface"
*.host1.eth[0].device = "tapa"
*.host1.eth[0].copyConfiguration = "copyFromExt"

*.host2.eth[0].typename = "ExtUpperEthernetInterface"
*.host2.eth[0].device = "tapb"
*.host2.eth[0].copyConfiguration = "copyFromExt"





                             
*.router.ipv4.natTable.config = xml("<config> \
                                        <entry type='prerouting' \
                                        packetFilter='has(Ipv4Header) &amp;&amp; Ipv4Header.protocolId != 1 &amp;&amp; Ipv4Header.destAddress.str() == \"192.168.2.99\"' \
                                        srcAddress='192.168.4.99' destAddress='192.168.4.98'/> \
                                        <entry type='prerouting' \
                                        packetFilter='has(Ipv4Header) &amp;&amp; Ipv4Header.protocolId != 1 &amp;&amp; Ipv4Header.destAddress.str() == \"192.168.4.99\"' \
                                        srcAddress='192.168.2.99' destAddress='192.168.2.20'/> \
                                     </config>")

*.routerMobile.ipv4.natTable.config = xml("<config> \
                                        <entry type='prerouting' \
                                        packetFilter='has(Ipv4Header) &amp;&amp; Ipv4Header.protocolId != 1 &amp;&amp; Ipv4Header.destAddress.str() == \"192.168.4.98\"' \
                                        srcAddress='192.168.3.99' destAddress='192.168.3.20'/> \
                                        <entry type='prerouting' \
                                        packetFilter='has(Ipv4Header) &amp;&amp; Ipv4Header.protocolId != 1 &amp;&amp; Ipv4Header.destAddress.str() == \"192.168.3.99\"' \
                                        srcAddress='192.168.4.98' destAddress='192.168.4.99'/> \
                                     </config>")
                                     
#*.router.ipv4.natTable.config = xml(
#"<config> 
#  <!-- NAT para pacotes indo para o servidor iperf -->
#  <entry type='prerouting'
#         packetFilter='has(Ipv4Header) &amp;&amp; Ipv4Header.protocolID.str() == \"17\" &amp;&amp; Ipv4Header.destAddress.str() == \"192.168.2.99\"'
#         srcAddress='192.168.3.99'
#         destAddress='192.168.3.20'/>
#
#  <!-- NAT para pacotes de volta do servidor iperf -->
#  <entry type='prerouting'
#         packetFilter='has(Ipv4Header) &amp;&amp; Ipv4Header.protocolID.str() == \"17\" &amp;&amp; Ipv4Header.destAddress.str() == \"192.168.3.99\"'
#         srcAddress='192.168.2.99'
#         destAddress='192.168.2.20'/>
#</config>")
#                                        <entry type='prerouting' \
#                                        packetFilter='has(Ipv4Header) &amp;&amp; Ipv4Header.destAddress.str() == \"192.168.3.99\"' \
#                                        srcAddress='192.168.2.99' destAddress='192.168.2.20'/> \


*.visualizer.*.interfaceTableVisualizer.displayInterfaceTables = true
*.visualizer.*.interfaceTableVisualizer.nodeFilter = "not name=~switch*"

**.duplexMode = true
**.eth*.bitrate = 100Mbps

*.radioMedium.analogModel.ignorePartialInterference = true
# channel physical parameters
**.mgmt.numChannels = 5

# Configuração dos APs
**.ap1.wlan[*].mgmt.ssid = "ap1"
**.ap2.wlan[*].mgmt.ssid = "ap2"
**.ap*.wlan[*].mgmt.beaconInterval = 100ms

# Canais Wi‑Fi
**.ap1.wlan[*].address = "10:00:00:00:00:00"
**.ap2.wlan[*].address = "20:00:00:00:00:00"
**.ap1.wlan[*].radio.channelNumber = 2
**.ap2.wlan[*].radio.channelNumber = 3
**.routerMobile.wlan[*].radio.channelNumber = 0  # será redefinido no escaneamento
**.wlan[*].mgmt.numAuthSteps = 4

# Potência do transmissor e alcance
**.radio.transmitter.power = 2mW

# Parâmetros de escaneamento do agente 802.11
**.wlan[*].agent.activeScan = true
**.wlan[*].agent.channelsToScan = ""           # escaneia todos
**.wlan[*].agent.probeDelay = 0.1s
**.wlan[*].agent.minChannelTime = 0.15s
**.wlan[*].agent.maxChannelTime = 0.3s
**.wlan[*].agent.defaultSsid = ""
**.wlan[*].agent.authenticationTimeout = 5s
**.wlan[*].agent.associationTimeout = 5s

# Visualização (opcional)
*.visualizer.physicalLinkVisualizer.displayLinks = true
*.ap*.wlan[*].radio.displayCommunicationRange = true

# wireless configuration
#**.wlan*.bitrate = 100Mbps #Original 2Mbps 
*.*.wlan*.opMode = "g(erp)"
*.*.wlan*.bitrate = 54Mbps

**.constraintAreaMinX = 0m
**.constraintAreaMaxX = 1000m
**.constraintAreaMinY = 0m
**.constraintAreaMaxY = 400m

*.routerMobile.mobility.typename = "CircleMobility"
*.routerMobile.mobility.cx = 650m
*.routerMobile.mobility.cy = 50m
*.routerMobile.mobility.r = 85m
*.routerMobile.mobility.speed = 40mps
*.routerMobile.mobility.startAngle = 90deg

*.physicalEnvironment.ground.typename = "FlatGround"
*.physicalEnvironment.ground.elevation = 0m
*.radioMedium.pathLoss.typename = "LogNormalShadowing"


[UmMovel]

network = VideoStreamingShowcaseMobile
*.configurator.config = xml("<config> \
                                <interface hosts='router' names='eth0' address='192.168.2.99' netmask='255.255.255.0'/> \
                                <interface hosts='router' names='eth1' address='192.168.4.99' netmask='255.255.255.0'/> \
                                <interface hosts='routerMobile' names='wlan0' address='192.168.4.98' netmask='255.255.255.0'/> \
                                <interface hosts='routerMobile' names='eth0' address='192.168.3.99' netmask='255.255.255.0'/> \
                            </config>")

[DoisMoveis]

network = VideoStreamingShowcaseTwoMobiles

*.configurator.config = xml("<config> \
                                <interface hosts='router' names='eth0' address='192.168.2.99' netmask='255.255.255.0'/> \
                                <interface hosts='router' names='eth1' address='192.168.4.99' netmask='255.255.255.0'/> \
                                <interface hosts='routerMobile' names='wlan0' address='192.168.4.98' netmask='255.255.255.0'/> \
                                <interface hosts='routerMobile' names='eth0' address='192.168.3.99' netmask='255.255.255.0'/> \
                                <interface hosts='host3' names='wlan0' address='192.168.4.97' netmask='255.255.255.0'/> \
                                <interface hosts='host4' names='eth0' address='192.168.2.97' netmask='255.255.255.0'/> \
                            </config>")


## udp apps
**.host4.numApps = 1
**.host4.app[0].typename = "UdpBasicApp"
**.host4.app[0].localPort = -1
**.host4.app[0].sendInterval = 1s
**.host4.app[0].messageLength = 1000B
**.host4.app[0].stopTime = 250s

**.host3.numApps = 1
**.host3.app[0].typename = "UdpEchoApp"
**.host3.app[0].localPort = 1000

**.host4.app[0].destAddresses = "host3"
**.host4.app[0].destPort = 1000
